package migrations

import (
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedHeader = "// Code generated by gogo makemigrations; DO NOT EDIT."

// MustDecode is intended only for static generated migration source.
func MustDecode(data string) Migration {
	var migration Migration
	if err := json.Unmarshal([]byte(data), &migration); err != nil {
		panic("migrations: malformed generated migration")
	}
	if _, err := migration.Checksum(); err != nil {
		panic(err)
	}
	return migration
}
func Generate(directory string, migration Migration) (string, error) {
	for _, operation := range migration.Operations {
		if operation.Forward != nil || operation.Backward != nil {
			return "", errors.New("migrations: write callback migrations as explicit Go source")
		}
	}
	if !migrationName.MatchString(migration.Name) {
		return "", errors.New("migrations: invalid migration filename")
	}
	if _, err := migration.Checksum(); err != nil {
		return "", err
	}
	absolute, err := filepath.Abs(directory)
	if err != nil {
		return "", err
	}
	for path := absolute; path != filepath.Dir(path); path = filepath.Dir(path) {
		info, err := os.Lstat(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return "", err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return "", errors.New("migrations: source directory must not contain symlinks")
		}
	}
	if err := os.MkdirAll(absolute, 0755); err != nil {
		return "", err
	}
	registryPath := filepath.Join(absolute, "registry.go")
	if data, err := os.ReadFile(registryPath); err == nil {
		if !strings.HasPrefix(string(data), generatedHeader) {
			return "", errors.New("migrations: refusing to replace a user-owned registry.go")
		}
	} else if !os.IsNotExist(err) {
		return "", err
	}
	path := filepath.Join(absolute, migration.Name+".go")
	if _, err := os.Lstat(path); err == nil {
		return "", errors.New("migrations: migration source already exists")
	} else if !os.IsNotExist(err) {
		return "", err
	}
	data, err := json.Marshal(migration)
	if err != nil {
		return "", err
	}
	source := fmt.Sprintf("%s\npackage migrations\nimport gogoMigrations %q\nvar Migration_%s = gogoMigrations.MustDecode(%q)\n", generatedHeader, "github.com/Newton-School/gogo/core/migrations", migration.Name, string(data))
	formatted, err := format.Source([]byte(source))
	if err != nil {
		return "", err
	}
	file, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0644)
	if err != nil {
		return "", err
	}
	_, writeErr := file.Write(formatted)
	closeErr := file.Close()
	if err := errors.Join(writeErr, closeErr); err != nil {
		return "", err
	}
	entries, err := os.ReadDir(absolute)
	if err != nil {
		return path, err
	}
	names := []string{}
	for _, entry := range entries {
		if entry.IsDir() || entry.Name() == "registry.go" || !strings.HasSuffix(entry.Name(), ".go") || strings.HasSuffix(entry.Name(), "_test.go") {
			continue
		}
		contents, err := os.ReadFile(filepath.Join(absolute, entry.Name()))
		if err != nil {
			return path, err
		}
		if strings.HasPrefix(string(contents), generatedHeader) {
			name := strings.TrimSuffix(entry.Name(), ".go")
			if !migrationName.MatchString(name) {
				return path, errors.New("migrations: invalid generated migration file")
			}
			names = append(names, "Migration_"+name)
		}
	}
	sort.Strings(names)
	registry := fmt.Sprintf("%s\npackage migrations\nimport gogoMigrations %q\nvar All = []gogoMigrations.Migration{%s}\n", generatedHeader, "github.com/Newton-School/gogo/core/migrations", strings.Join(names, ","))
	formatted, err = format.Source([]byte(registry))
	if err != nil {
		return path, err
	}
	temporary, err := os.CreateTemp(absolute, ".registry-*.go")
	if err != nil {
		return path, err
	}
	tmpName := temporary.Name()
	defer os.Remove(tmpName)
	if _, err := temporary.Write(formatted); err != nil {
		temporary.Close()
		return path, err
	}
	if err := temporary.Chmod(0644); err != nil {
		temporary.Close()
		return path, err
	}
	if err := temporary.Close(); err != nil {
		return path, err
	}
	return path, os.Rename(tmpName, registryPath)
}
