package management

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"reflect"
	"strconv"
	"strings"

	"github.com/Newton-School/gogo/core/models"
)

func inspectionSource(namespace string, modelsToRender []inspectedModel, options InspectDBOptions) ([]byte, error) {
	pkg := options.Package
	if pkg == "" {
		pkg = options.AppLabel
	}
	var output bytes.Buffer
	fmt.Fprintf(&output, "// Generated by inspectdb for developer review; these models are unmanaged.\n// Configure the model backend to use database schema %q.\n// No migration ownership or baseline equivalence has been verified.\npackage %s\n\n", namespace, pkg)
	if len(modelsToRender) == 0 {
		return format.Source(output.Bytes())
	}
	fmt.Fprintln(&output, "import (\n\"github.com/Newton-School/gogo/core/models\"")
	usedTime, usedJSON := false, false
	for _, model := range modelsToRender {
		for _, field := range model.fields {
			usedTime = usedTime || strings.Contains(field.goType, "time.Time")
			usedJSON = usedJSON || strings.Contains(field.goType, "json.RawMessage")
		}
	}
	if usedTime {
		fmt.Fprintln(&output, "\"time\"")
	}
	if usedJSON {
		fmt.Fprintln(&output, "\"encoding/json\"")
	}
	fmt.Fprintln(&output, ")")
	for _, model := range modelsToRender {
		fmt.Fprintf(&output, "\n// Database relation %q, kind %q.\n", model.catalog.Name, model.catalog.Kind)
		if len(options.PrimaryKeys[model.catalog.Name]) > 0 {
			fmt.Fprintln(&output, "// Row identity is explicitly developer-declared, not a database primary-key proof.")
		}
		for _, column := range model.catalog.Columns {
			fmt.Fprintf(&output, "// Column %q: native type %q; identity %q; generated %q.\n", column.Name, column.DatabaseType, column.Identity, column.Generated)
		}
		for _, constraint := range model.catalog.Constraints {
			fmt.Fprintf(&output, "// Database constraint %q: %q\n", constraint.Name, constraint.Definition)
		}
		for _, index := range model.catalog.Indexes {
			fmt.Fprintf(&output, "// Database index %q: %q\n", index.Name, index.Definition)
		}
		fmt.Fprintf(&output, "type %s struct {\n models.Base\n", model.schema.Name)
		for _, field := range model.fields {
			fmt.Fprintf(&output, "%s %s\n", field.field.StructField, field.goType)
		}
		fmt.Fprintf(&output, "}\n\nfunc (*%s) Schema() models.Schema {\n return models.Schema{\nAppLabel:%q, Name:%q,Table:%q,Unmanaged:true,\n", model.schema.Name, model.schema.AppLabel, model.schema.Name, model.schema.Table)
		for _, metadata := range []struct {
			name  string
			value any
		}{{"PrimaryKey", model.schema.PrimaryKey}, {"Indexes", model.schema.Indexes}, {"Constraints", model.schema.Constraints}, {"Comment", model.schema.Comment}, {"Tablespace", model.schema.Tablespace}} {
			literal, err := inspectionLiteral(reflect.ValueOf(metadata.value), 0)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&output, "%s:%s,\n", metadata.name, literal)
		}
		fmt.Fprintln(&output, "Fields: []models.Field{")
		for _, field := range model.fields {
			literal, err := inspectionLiteral(reflect.ValueOf(field.field), 0)
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&output, "models.NewField(%q, %q, models.WithStructField(%q), func(f *models.Field) { *f = %s }),\n", field.field.Name, field.field.Kind, field.field.StructField, literal)
		}
		fmt.Fprintln(&output, "},\n}\n}")
		if output.Len() > 8<<20 {
			return nil, errors.New("inspectdb: generated source exceeds 8 MiB")
		}
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, err
	}
	if len(formatted) > 8<<20 {
		return nil, errors.New("inspectdb: generated source exceeds 8 MiB")
	}
	return formatted, nil
}

// Only primitive and model-descriptor values can become Go literals. Runtime
// callbacks/custom objects never become code, and all source strings are quoted.
func inspectionLiteral(v reflect.Value, depth int) (string, error) {
	if depth > 16 {
		return "", errors.New("inspectdb: descriptor nesting exceeds source limit")
	}
	if !v.IsValid() {
		return "nil", nil
	}
	switch v.Kind() {
	case reflect.String:
		return strconv.Quote(v.String()), nil
	case reflect.Bool:
		return strconv.FormatBool(v.Bool()), nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return strconv.FormatInt(v.Int(), 10), nil
	case reflect.Pointer:
		if v.IsNil() {
			return "nil", nil
		}
		value, err := inspectionLiteral(v.Elem(), depth+1)
		if err != nil {
			return "", err
		}
		if v.Elem().Kind() == reflect.Struct {
			return "&" + value, nil
		}
		if v.Elem().Kind() == reflect.Bool {
			return "func() *bool { v := " + value + "; return &v }()", nil
		}
	case reflect.Slice:
		if v.IsNil() {
			return "nil", nil
		}
		if v.Len() > 1600 {
			return "", errors.New("inspectdb: descriptor list exceeds source limit")
		}
		var items []string
		for i := 0; i < v.Len(); i++ {
			item, err := inspectionLiteral(v.Index(i), depth+1)
			if err != nil {
				return "", err
			}
			items = append(items, item)
		}
		typeName := v.Type().String()
		if typeName != "[]string" && !strings.HasPrefix(typeName, "[]models.") {
			return "", errors.New("inspectdb: unsupported descriptor slice type")
		}
		return typeName + "{\n" + strings.Join(items, ",\n") + func() string {
			if len(items) > 0 {
				return ","
			}
			return ""
		}() + "\n}", nil
	case reflect.Struct:
		if v.Type().PkgPath() != reflect.TypeFor[models.Field]().PkgPath() {
			return "", errors.New("inspectdb: unsupported descriptor value type")
		}
		var fields []string
		for i := 0; i < v.NumField(); i++ {
			if v.Field(i).IsZero() {
				continue
			}
			value, err := inspectionLiteral(v.Field(i), depth+1)
			if err != nil {
				return "", err
			}
			fields = append(fields, v.Type().Field(i).Name+":"+value)
		}
		return v.Type().String() + "{\n" + strings.Join(fields, ",\n") + func() string {
			if len(fields) > 0 {
				return ","
			}
			return ""
		}() + "\n}", nil
	}
	return "", errors.New("inspectdb: unsupported runtime value in model descriptor")
}
