// Code generated by gogo generate. DO NOT EDIT.
package catalog

import (
	"github.com/Newton-School/gogo/core/app"
	"github.com/Newton-School/gogo/core/orm"
	time "time"
)

var ProductFields = struct {
	ID          orm.Ref[int64]
	Name        orm.Ref[string]
	Slug        orm.Ref[string]
	Description orm.Ref[string]
	Price       orm.Ref[string]
	Stock       orm.Ref[int64]
	Published   orm.Ref[bool]
	CreatedAt   orm.Ref[time.Time]
}{
	ID:          orm.Field[int64]("id"),
	Name:        orm.Field[string]("name"),
	Slug:        orm.Field[string]("slug"),
	Description: orm.Field[string]("description"),
	Price:       orm.Field[string]("price"),
	Stock:       orm.Field[int64]("stock"),
	Published:   orm.Field[bool]("published"),
	CreatedAt:   orm.Field[time.Time]("created_at"),
}
var ProductNoteFields = struct {
	ID        orm.Ref[int64]
	ProductID orm.Ref[int64]
	Body      orm.Ref[string]
}{
	ID:        orm.Field[int64]("id"),
	ProductID: orm.Field[int64]("product"),
	Body:      orm.Field[string]("body"),
}

func registerModels(registry *app.Registry) error {
	{
		schema := (&Product{}).Schema()
		if err := schema.Validate(); err != nil {
			return err
		}
		if err := registry.Register("models", schema.Key(), schema); err != nil {
			return err
		}
	}
	{
		schema := (&ProductNote{}).Schema()
		if err := schema.Validate(); err != nil {
			return err
		}
		if err := registry.Register("models", schema.Key(), schema); err != nil {
			return err
		}
	}
	return nil
}
