// Code generated by gogo makemigrations; DO NOT EDIT.
package migrations

import gogoMigrations "github.com/Newton-School/gogo/core/migrations"

var All = []gogoMigrations.Migration{Migration_0001_initial}
