package postgres

import (
	"fmt"
	"github.com/Newton-School/gogo/core/db"
	"github.com/Newton-School/gogo/core/models"
	"strings"
)

type Dialect struct{ Capabilities db.Capabilities }

func (Dialect) Name() string { return "postgres" }
func (Dialect) QuoteIdentifier(name string) (string, error) {
	if !models.ValidIdentifier(name) {
		return "", fmt.Errorf("invalid SQL identifier")
	}
	return `"` + name + `"`, nil
}
func (Dialect) Placeholder(index int) string { return fmt.Sprintf("$%d", index) }
func (d Dialect) FieldType(f models.Field) (string, error) {
	switch f.Kind {
	case models.SmallInteger, models.PositiveSmallInteger:
		return "smallint", nil
	case models.Integer, models.PositiveInteger:
		return "integer", nil
	case models.BigInteger, models.PositiveBigInteger:
		return "bigint", nil
	case models.SmallAuto:
		return "smallint GENERATED BY DEFAULT AS IDENTITY", nil
	case models.Auto:
		return "integer GENERATED BY DEFAULT AS IDENTITY", nil
	case models.BigAuto:
		return "bigint GENERATED BY DEFAULT AS IDENTITY", nil
	case models.UUID:
		return "uuid", nil
	case models.Decimal:
		if f.MaxDigits < 1 || f.DecimalPlaces < 0 || f.DecimalPlaces > f.MaxDigits {
			return "", fmt.Errorf("invalid decimal precision")
		}
		return fmt.Sprintf("numeric(%d,%d)", f.MaxDigits, f.DecimalPlaces), nil
	case models.Float:
		return "double precision", nil
	case models.Boolean:
		return "boolean", nil
	case models.Char, models.Slug, models.Email, models.URL, models.FilePath, models.File, models.Image:
		if f.MaxLength > 0 {
			return fmt.Sprintf("varchar(%d)", f.MaxLength), nil
		}
		return "text", nil
	case models.Text:
		return "text", nil
	case models.GenericIPAddress:
		return "inet", nil
	case models.Date:
		return "date", nil
	case models.DateTime:
		return "timestamp with time zone", nil
	case models.Time:
		return "time without time zone", nil
	case models.Duration:
		return "interval", nil
	case models.Binary:
		return "bytea", nil
	case models.JSON:
		return "jsonb", nil
	case models.ForeignKey, models.OneToOne:
		return "bigint", nil
	case models.Array:
		if f.Element == nil {
			return "", fmt.Errorf("array element missing")
		}
		value, err := d.FieldType(*f.Element)
		if err != nil {
			return "", err
		}
		if f.Element.IsAuto() {
			return "", fmt.Errorf("array cannot contain identity")
		}
		return value + "[]", nil
	case models.HStore:
		if !d.Capabilities["extension:hstore"] {
			return "", &db.Error{Code: db.UnsupportedFeature, Message: "hstore extension required"}
		}
		return "hstore", nil
	case models.Range:
		switch f.RangeType {
		case models.Integer:
			return "int4range", nil
		case models.BigInteger:
			return "int8range", nil
		case models.Decimal:
			return "numrange", nil
		case models.Date:
			return "daterange", nil
		case models.DateTime:
			return "tstzrange", nil
		}
		return "", fmt.Errorf("range base type unsupported")
	case models.SearchVector:
		return "tsvector", nil
	case models.Geometry, models.Geography, models.Raster:
		if !d.Capabilities["extension:postgis"] {
			return "", &db.Error{Code: db.UnsupportedFeature, Message: "PostGIS extension required"}
		}
		return string(f.Kind), nil
	case models.Generated:
		if f.Element == nil || f.GeneratedExpression == "" {
			return "", fmt.Errorf("generated field needs expression and output field")
		}
		base, err := d.FieldType(*f.Element)
		if err != nil {
			return "", err
		}
		if strings.Contains(f.GeneratedExpression, ";") {
			return "", fmt.Errorf("generated expression cannot contain statements")
		}
		return base + " GENERATED ALWAYS AS (" + f.GeneratedExpression + ") STORED", nil
	}
	return "", &db.Error{Code: db.UnsupportedFeature, Message: "Unsupported PostgreSQL field type"}
}
