// Code generated by gogo generate. DO NOT EDIT.
package catalog

import (
	"github.com/Newton-School/gogo/core/app"
	"github.com/Newton-School/gogo/core/orm"
)

var ProductFields = struct {
	ID   orm.Ref[int32]
	Name orm.Ref[string]
}{
	ID:   orm.Field[int32]("id"),
	Name: orm.Field[string]("name"),
}

func registerModels(registry *app.Registry) error {
	{
		schema := (&Product{}).Schema()
		if err := schema.Validate(); err != nil {
			return err
		}
		if err := registry.Register("models", schema.Key(), schema); err != nil {
			return err
		}
	}
	return nil
}
